build:
 stage: build
 script:
 - cd src
 - mvn clean install

 artifacts:
   paths:
   - src/ear/target/eaas-server.ear

deploy:
 stage: deploy
 script:
 - sshpass -p $gitlab rsync -e "ssh -o StrictHostKeyChecking=no" -rltvz -O ear/target/eaas-server.ear gitlab@192.52.32.102:/mnt/data/citar-demo/deployments/eaas-server.ear

cache:
  paths:
  - /root/.m2/