image: maven:3-jdk-8


before_script:
 - cp -r .m2 /root/ || true

after_script:
 - cp -r /root/.m2 .
 - cp src/ear/target/eaas-server.ear .
  
standalone-server-build:
  script:
  - mvn -f src/pom.xml clean install
  artifacts:
    paths:
    - eaas-server.ear
  cache:
    paths:
    - .m2 
    
emucomp-build:
  script: 
    - ln -fs deployment-emucomp.xml src/ear/src/main/application/META-INF/jboss-deployment-structure.xml
    - mvn -f src/pom.xml clean install -P emucomp -pl ear -am
  artifacts:
   paths:
    - eaas-server.ear
  cache:
   paths:
    - .m2
    
gateway-build:
  script: 
    - ln -fs deployment-gateway.xml src/ear/src/main/application/META-INF/jboss-deployment-structure.xml
    - mvn -f src/pom.xml clean install -P '!emucomp' -pl ear -am
  artifacts:
   paths:
    - eaas-server.ear
  cache:
   paths:
    - .m2
    
trigger:
  stage: deploy
  script:
   - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=master https://gitlab.com/api/v4/projects/11165186/trigger/pipeline
  only:
   refs:
     - emil-db-rework
   variables:
     - $CI_PROJECT_NAMESPACE == "openslx"