image: maven:3-jdk-8




build:
 stage: build
 script:
 - cd src
 - find / -type d -name ".m2"
 - mvn clean install
 - ls -la /root/.m2

 artifacts:
   paths:
   - src/ear/target/eaas-server.ear

deploy:
 stage: deploy
 before_script:
  - apt-get update -qq && apt-get install -y rsync sshpass
 script:
 - sshpass -p $gitlab rsync -e "ssh -o StrictHostKeyChecking=no" -rltvz -O ear/target/eaas-server.ear gitlab@192.52.33.121:/mnt/data/citar-demo/deployments/eaas-server.ear

cache:
  paths:
  - /root/.m2
  