image: maven:3-jdk-8

before_script:
  - cd src
  - cp -r .m2 /root/ || true
after_script:
  - cp -r /root/.m2 .

server-build:
  script:
  - mvn clean install
  - cp -r /root/.m2 .
  artifacts:
    paths:
    - src/ear/target/eaas-server.ear
  cache:
    paths:
    - src/.m2 
    
emucomp-build:
  script: 
    - ln -fs ear/src/main/application/META-INF/deployment-emucomp.xml ear/src/main/application/META-INF/jboss-deployment-structure.xml
    - mvn -f pom.xml clean install -P emucomp -pl ear -am
  artifacts:
   paths:
    - src/ear/target/eaas-server.ear
  cache:
   paths:
    - .m2
