image: maven:3-jdk-8

before_script:
  - apt-get update -qq && apt-get install -y rsync sshpass

build:
  script:
  - cd src
  - mvn clean install
  - sshpass -p $gitlab rsync -e "ssh -o StrictHostKeyChecking=no" -rltvz -O ear/target/eaas-server.ear gitlab@192.52.32.102:/mnt/data/citar-demo/deployments/eaas-server.ear

  artifacts:
    paths:
    - src/ear/target/eaas-server.ear

 cache:
   key: ${CI_COMMIT_REF_SLUG}
   paths:
   - /root/.m2/