image: maven:3-jdk-8



before_script:
  - cd src
  - cp -r .m2 /root/ || true
after_script:
  - cp -r /root/.m2 .
  - cp src/ear/target/eaas-server.ear .
  


standalone-server-build:
  script:
  - mvn clean install
  artifacts:
    paths:
    - eaas-server.ear
  cache:
    paths:
    - .m2 
    
emucomp-build:
  script: 
    - ln -fs ear/src/main/application/META-INF/deployment-emucomp.xml ear/src/main/application/META-INF/jboss-deployment-structure.xml
    - mvn -f pom.xml clean install -P emucomp -pl ear -am
  artifacts:
   paths:
    - eaas-server.ear
  cache:
   paths:
    - .m2
    
gateway-build:
  script: 
    - ln -fs ear/src/main/application/META-INF/deployment-gateway.xml ear/src/main/application/META-INF/jboss-deployment-structure.xml
    - mvn -f pom.xml clean install -P '!emucomp' -pl ear -am
  artifacts:
   paths:
    - eaas-server.ear
  cache:
   paths:
    - .m2
    
trigger:
  stage: deploy
  trigger: openslx/emucomp-image-builder